@ECHO OFF

SET VSVERSION_2013=12.0
SET VSVERSION_2015=14.0
SET VSVERSION=%VSVERSION_2015%

IF NOT DEFINED DevEnvDir (
    CALL "C:\Program Files (x86)\Microsoft Visual Studio %VSVERSION%\VC\vcvarsall.bat" x86_amd64
)

SET OUTPUTDIR="%~dp0build"
SET INCLUDES=-I..\include -I..\src
SET DEFINES=/D UNICODE /D _UNICODE /D BUILD_STATIC
SET CPPFLAGS=%INCLUDES% /FC /nologo /W4 /WX /Zi
SET LIBRARIES=User32.lib Gdi32.lib
SET LNKFLAGS=%LIBRARIES%

IF NOT EXIST %OUTPUTDIR% mkdir %OUTPUTDIR%

PUSHD %OUTPUTDIR%
cl %CPPFLAGS% ..\src\win32_game.cc %DEFINES% %LNKFLAGS% /Fegame.exe
POPD

